name: Receive Report
description: Helper to receive the report from another repositories workflow
inputs:
  result:
    required: true
    description: true/false result of the run
  message:
    required: false
    description: A message describing the failure if needed
    default: No message provided
runs:
  using: composite
  steps:
    - name: Report the results
      shell: bash
      run: |
        RESULT="${{ inputs.result }}""
        MESSAGE="${{ inputs.message }}"
        if [ "$RESULT" = "false" ]; then
          echo "Outside workflow failed"
          echo "${{ inputs.message }}"
          exit 1
        fi
        echo "Outside workflow passed!"
