name: Start Workflow
description: Helper to kick off private workflow from public repo
inputs:
  repository:
    required: true
    description: The repository to Run
  ref:
    required: true
    description: The repository branch or sha to run the workflow in
  workflow:
    required: true
    description: The workflow in the repository to run
  workflow_to_report_to:
    required: true
    description: The workflow to send the report back to
  token:
    required: true
    description: The GITHUB_TOKEN with access to run workflows on private/internal repos
  inputs:
    required: false
    description: "Inputs for the workflow as json, for examples see: https://cli.github.com/manual/gh_workflow_run"
    default: "{}"
runs:
  using: composite
  steps:
    - name: trigger
      shell: bash
      run: |
        echo "Making call to private repo to start workflow"
        GITHUB_TOKEN=${{ inputs.token }}
        export GITHUB_TOKEN
        SENDING_BRANCH=$(echo ${GITHUB_REF#refs/heads/})
        echo "${{ inputs.inputs }}" | gh workflow run ${{ inputs.workflow }} -R ${{ inputs.repository }} --ref ${{ inputs.ref }} -f sending_repository=${{ github.repository }} -f sending_branch=${SENDING_BRANCH} -f reporting_workflow=${{ inputs.workflow_to_report_to }} --json
