name: Send Report
description: Helper to send reports from a workflow back to the branch/pr that starting the workflow
inputs:
  sending_branch:
    required: true
    description: The branch the sent the request for tests to run
  sending_repository:
    required: true
    description: The repository that sent the request for the tests to run
  workflow_to_report_to:
    required: true
    description: The workflow to send the report back to
  result:
    required: true
    description: true/false result of the run
  message:
    required: false
    description: A message describing the failure if needed
    default: No message provided
  token:
    required: true
    description: The GITHUB_TOKEN with access to run workflows on private/internal repos
  inputs:
    required: false
    description: "Inputs for the workflow as json, for examples see: https://cli.github.com/manual/gh_workflow_run"
    default: "{}"
runs:
  using: composite
  steps:
    - name: trigger
      shell: bash
      run: |
        echo "make api call to gh "
        GITHUB_TOKEN=${{ inputs.token }}
        export GITHUB_TOKEN
        SENDING_BRANCH=$(echo ${GITHUB_REF#refs/heads/})
        echo "${{ inputs.inputs }}" | gh workflow run ${{ inputs.workflow_to_report_to }} -R ${{ inputs.sending_repository }} --ref ${{ inputs.sending_branch }} -f result=${{ inputs.result }} -f message="${{ inputs.message }}" --json
