name: Run Private Workflow
description: Helper to run a private workflow and wait for it to finish
inputs:
  token:
    required: true
    description: The github token with permissions to access the repository with the workflow you want to poll
  owner:
    required: false
    description: The repository owner
    default: smartcontractkit
  repository:
    required: true
    description: The repository name
  ref:
    required: true
    description: The repository branch or sha to use as the ref for the workflows
  workflow_file:
    required: true
    description: The workflow filename
  inputs:
    required: false
    description: "Inputs for the workflow as json, for examples see: https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event"
    default: "{}"
  timeout:
    required: false
    description: The total time to wait for the workflow to finish, as a go time.Duration string
    default: 5m
  retry_interval:
    required: false
    description: The amount of time to wait between polls of the service, as a go time.Duration string
    default: 15s
outputs:
  status:
    description: The status of the workflow
  conclusion:
    description: The result of the workflow
  workflow_id:
    description: The id of the workflow, can be used to pull further results or logs if needed
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TOKEN: ${{ inputs.token }}
    OWNER: ${{ inputs.owner }}
    REPOSITORY: ${{ inputs.repository }}
    REF: ${{ inputs.ref }}
    WORKFLOW_FILE: ${{ inputs.workflow_file }}
    INPUTS: ${{ inputs.inputs }}
    TIMEOUT: ${{ inputs.timeout }}
    RETRY_INTERVAL: ${{ inputs.retry_interval }}
