name: public to private test
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: public-to-private-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tester:
    name: Start and poll the test
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' 
    steps:
      - name: Checkout the repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: ./public-to-private/run-workflow
        id: poll
        with:
          token: ${{ github.token }}
          repository: chainlink-github-actions
          ref: public_to_private
          workflow_file: public-to-private-test.yml
          timeout: 10m
      - name: get outputs
        run: |
          echo "status = ${{ steps.poll.outputs.status }}"
          echo "conclusion = ${{ steps.poll.outputs.conclusion }}"
          echo "workflow_id = ${{ steps.poll.outputs.workflow_id }}"
          if [ "${{ steps.poll.outputs.status }}" != "success" ]; then
            exit 1
          fi
  sleeper:
    name: Just sleep for 1 minute to make the test poll for a bit
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' 
    steps:
      - name: Sleep
        run: sleep 60
