name: public to private test
on:
  pull_request:

concurrency:
  group: public-to-private-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tester:
    name: Start and poll the test
    runs-on: ubuntu-latest
    environment: integration
    steps:
      - name: Checkout the repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: ./public-to-private/run-workflow
        id: poll
        with:
          token: ${{ secrets.TMP_TEST_TOKEN }}
          repository: chainlink-github-actions
          ref: public_to_private
          workflow_file: testtopoll.yml
          timeout: 10m
      - name: get outputs
        run: |
          echo "status = ${{ steps.poll.outputs.status }}"
          echo "conclusion = ${{ steps.poll.outputs.conclusion }}"
